apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: my-app-pipeline-
spec:
  pipelineRef:
    name: my-app-pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
