on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  push:
    branches:
      - main 
    paths:
      - 'charts/**'

name: Lint the Kubernetes charts 

jobs:
  kubeval:
    name: lint the charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Create helm template outputs 
        run: |
          mkdir helm-output
          cd ./charts/my-app
          helm dep up
          cd ../../
          helm template ./charts/my-app >> ./helm-output/be-ci.yaml 
          helm template ./charts/my-app -f ./charts/my-app/values-demo.yaml >> ./helm-output/be-demo.yaml 
          helm template ./charts/my-app -f ./charts/my-app/values-pro.yaml >> ./helm-output/be-pro.yaml 
          helm template ./charts/bootstrap >> ./helm-output/bootstrap-ci.yaml 
          helm template ./charts/bootstrap -f ./charts/bootstrap/values-demo.yaml >> ./helm-output/bootstrap-demo.yaml 
          helm template ./charts/bootstrap -f ./charts/bootstrap/values-pro.yaml >> ./helm-output/bootstrap-pro.yaml
          ls -al ./helm-output/
  
      - name: Kube Eval the outputs 
        uses: instrumenta/kubeval-action@master
        with:
          files: helm-output/

      - name: Kube-linter Scan repo
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@v1.0.0
        with:
          directory: helm-output/
          config: .github/kube-lint/config.yaml
